---
- name: Sample Ansible Playbook with Issues
  hosts: localhost
  tasks:
    - name: Debug message (correct task)
      ansible.builtin.debug:
        msg: "This task is correct and will pass linting."

    # ISSUE: Missing `state` parameter in the package task
    - name: Install a package (linting issue missing 'state' parameter)
      ansible.builtin.apt:
        name: apache2
        state: present
