yamlCopy codename: Ansible Linting Pipelineon:push:branches:- mainpull_request:branches:- mainjobs:lint:runs-on: ubuntu-lateststeps:- name: Checkout codeuses: actions/checkout@v2- name: Install Python3 and piprun: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip- name: Install ansible-lint and yamllintrun: |
        pip3 install ansible-lint yamllint- name: Lint YAML filesrun: |
        yamllint **/*.yml- name: Lint Ansible Playbookrun: |
        ansible-lint **/*.yml
