name: Ansible Linting Pipeline
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  lint:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Install Python3 and pip
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
 
    - name: Install ansible-lint and yamllint
      run: |
        pip3 install ansible-lint yamllint
 
    - name: Lint YAML files
      run: |
        yamllint **/*.yml
 
    - name: Lint Ansible Playbook
      run: |
        ansible-lint **/*.yml
